php:
  preset: laravel
<<<<<<< HEAD
  version: 8
=======
>>>>>>> origin/them_slide
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
